"""
Supervised Fine-Tuning (SFT)
=============================

Fine-tunes KT_GPT on synthetic code reasoning data generated by data/synth.py.

Training format: [PROBLEM] -> [REASONING] -> [CODE] -> [TESTS]

Uses the same Trainer infrastructure as pretraining but with:
  - Much lower learning rate (5e-5)
  - Short training (1-2 epochs over SFT data)
  - No gradient accumulation needed (smaller dataset)
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import torch
from torch.utils.data import Dataset, DataLoader

from model.config import KTGPTConfig
from model.model import KTGPT
from train.pretrain import Trainer, TrainConfig


@dataclass
class SFTConfig(TrainConfig):
    """SFT-specific training configuration.

    Inherits from TrainConfig with overrides for fine-tuning:
    lower LR, shorter training, smaller batch.
    """
    phase: int = 3
    lr: float = 5e-5
    min_lr: float = 1e-6
    warmup_steps: int = 200
    weight_decay: float = 0.01
    grad_accum_steps: int = 8
    micro_batch_size: int = 4
    seq_len: int = 4096
    num_epochs: int = 2
    wandb_run_name: str = "sft"
    sft_data_path: str = "./data/synth_output.jsonl"

    # These will be computed from data size
    total_tokens: int = 0


class SFTDataset(Dataset):
    """Dataset for supervised fine-tuning on synthetic code reasoning data.

    Loads JSONL samples produced by data/synth.py, tokenizes them,
    and pads/truncates to seq_len.
    """

    def __init__(
        self,
        data_path: str,
        tokenizer,
        seq_len: int = 4096,
    ) -> None:
        self.seq_len = seq_len
        self.tokenizer = tokenizer
        self.samples: list[dict] = []

        # Load JSONL
        path = Path(data_path)
        if not path.exists():
            raise FileNotFoundError(f"SFT data not found: {data_path}")

        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                sample = json.loads(line.strip())
                if "text" in sample:
                    self.samples.append(sample)

        print(f"[SFT] Loaded {len(self.samples)} training samples from {data_path}")

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> dict[str, torch.Tensor]:
        text = self.samples[idx]["text"]
        token_ids = self.tokenizer.encode(text, add_special_tokens=True)

        # Truncate to seq_len
        if len(token_ids) > self.seq_len:
            token_ids = token_ids[:self.seq_len]

        # Pad to seq_len
        pad_len = self.seq_len - len(token_ids)
        if pad_len > 0:
            pad_id = self.tokenizer.pad_token_id or 0
            token_ids = token_ids + [pad_id] * pad_len

        ids = torch.tensor(token_ids, dtype=torch.long)
        return {"input_ids": ids, "labels": ids.clone()}


def run_sft(
    checkpoint_path: str,
    sft_data_path: str = "./data/synth_output.jsonl",
    output_dir: str = "./checkpoints/sft",
    num_epochs: int = 2,
) -> None:
    """Run SFT training on synthetic data.

    Args:
        checkpoint_path: Path to pretrained model checkpoint
        sft_data_path: Path to JSONL file from synth.py
        output_dir: Where to save SFT checkpoints
        num_epochs: Number of training epochs
    """
    from data.mix import get_tokenizer

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Load model from pretrained checkpoint
    model_config = KTGPTConfig()
    model = KTGPT(model_config).to(device=device, dtype=torch.bfloat16)

    # Load pretrained weights
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model"])
    print(f"[SFT] Loaded pretrained model from {checkpoint_path}")

    # Tokenizer
    tokenizer = get_tokenizer()

    # Dataset
    dataset = SFTDataset(sft_data_path, tokenizer, seq_len=model_config.max_seq_len)

    # Config
    sft_config = SFTConfig()
    sft_config.sft_data_path = sft_data_path
    sft_config.checkpoint_dir = output_dir
    sft_config.num_epochs = num_epochs
    sft_config.total_tokens = len(dataset) * model_config.max_seq_len * num_epochs

    # DataLoader
    dataloader = DataLoader(
        dataset,
        batch_size=sft_config.micro_batch_size,
        shuffle=True,
        drop_last=True,
        num_workers=2,
    )

    # Train
    trainer = Trainer(model=model, config=sft_config, device=device)

    for epoch in range(num_epochs):
        print(f"\n[SFT] Epoch {epoch + 1}/{num_epochs}")
        trainer.train(dataloader)

    print(f"\n[SFT] Training complete. Checkpoints saved to {output_dir}")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="KT_GPT Supervised Fine-Tuning")
    parser.add_argument("--checkpoint", required=True, help="Pretrained checkpoint path")
    parser.add_argument("--data", default="./data/synth_output.jsonl")
    parser.add_argument("--output-dir", default="./checkpoints/sft")
    parser.add_argument("--epochs", type=int, default=2)
    args = parser.parse_args()

    run_sft(args.checkpoint, args.data, args.output_dir, args.epochs)
